= Cryptographic Capability Computing (C3) Simulator
:source-highlighter: pygments
:source-language: bash

:ispm-base: intel-simics-package-manager-1.1.0
:simics-base: /opt/simics/simics-6.0.157
:simics-pkg-ver: 2022.49
:simics-pkg-ver-stem: simics-6-packages-2022-49-linux64
:simics-repo-url: https://github.com/IntelLabs/c3-simulator.git
:CKPT_NOKERNEL_BASE: /opt/simics/checkpoints/glibc_latest.ckpt
:CKPT_KERNEL_BASE: /opt/simics/checkpoints/ubuntu-20.4_latest.ckpt
:CKPT_GLIBC: checkpoints/cc_glibc.ckpt
:CKPT_LLVM: checkpoints/cc_llvm.ckpt
:CKPT_KERNEL: checkpoints/cc_kernel.ckpt
:SIMICS_BIN: /opt/simics/simics-6/simics-latest/bin

WARNING: The contents of this repository and linked repositories are solely for
research purposes and may contain software with vulnerabilities, such as
outdated libraries. Do not use in production.

This material is based upon work supported by the Naval Information Warfare
Center Pacific and the Defense Advanced Research Project Agency under Prototype
Other Transaction Agreement No. N66001-22-9-4017. Any opinions, findings and
conclusions or recommendations expressed in this material are those of the
author(s) and do not necessarily reflect the views of the Space and Naval
Warfare Systems Center Pacific or the Defense Advanced Research Project Agency.

== Installation

=== Clone source code

[source,subs=attributes]
----
git clone --recurse-submodules {simics-repo-url}
----

=== Download and install required packages

==== Install Simcis




Download and install Simics v.{simics-pkg-ver} from https://software.intel.com/content/www/us/en/develop/articles/simics-simulator.html.

Create an `/opt/simics` directory owned by the current user.

The following commands can be executed in a directory where both the Simics
package bundle and the package manager archive have been downloaded to install
Simics:

[source,subs=attributes]
----
tar xf {ispm-base}.tar.gz
{ispm-base}/ispm packages --install-bundle {simics-pkg-ver-stem}.ispm --install-dir {simics-base} --non-interactive
----

Next, launch the package manager GUI with `{ispm-base}/ispm-gui` to associate the needed addons with the Simics base package using the following steps:

1. Click the "Addons" tab.
2. Select "QSP-x86", "QSP-Clear-Linux", and "QSP-CPU".
3. Client "Save updates".
4. Close the package manager GUI.

The Simics VMP module should be installed and enabled if possible to significantly accelerate simulation:

[source,subs=attributes]
----
{simics-base}/bin/vmp-kernel-install
----

==== Install other dependencies

On Ubuntu 20.04, dependencies can be installed with `make -f config-local.mk
install_dependencies` (use `make -n` to dry-run, as this will use `sudo`).
Alternatively, you may manually install the following dependencies:

* bison
* curl
* flex
* git
* g++-8
* libatk1.0-dev
* libatk-bridge2.0-dev
* libgtk3-dev
* python-3-pip
* pytest with xdist (install with 'pip3 install pytest-xdist')

=== Initialize and build Simics project

Most of the configuration, build, and install commands use Makefiles. You can
use `make -n <target>` to dry-run and view commands make would execute.

==== (Optional) Configure makefile targets

The code listing below assume default paths, but these can be configured by
creating a `config-local.mk` file or setting the corresponding environment
variables. Some relevant variables and their default values are:

SIMICS_BIN :: The path to Simics installation bin directory (default:
{simics_bin})

CKPT_NOKERNEL_BASE :: Path for a base no-kernel checkpoint that is used as the
starting point when generating checkpoints without custom kernel. If not set,
new checkpoints will be created from scratch. Default value is ignored if path
is not found.  (default: `{ckpt_nokernel_base}`)

CKPT_GLIBC :: Path for checkpoint with glibc, this is generated with `make
ckpt-cc_gblic`, and will be a symlink to tagged checkpoint folder (default:
{ckpt_glibc})

CKPT_LLVM :: Similar to CKPT_GLIBC, but includes llvm (default: {ckpt_llvm})

=== (Optional) Cleaning build artifacts and files

To clean Simics modules:
----
make clean
----

To clean moost build artifacts (e.g., for glibc, llvm, and linux), run:

----
make mrproper
----

Neither of the commands will remove checkpoints, to do so delete the checkpoints
folder(s) manually. Note that checkpoints by default depend on the originating
checkpoint, e.g., on CKPT_NOKERNEL_BASE, if used when createing subsequent
checkpoints.

==== Initialize Simics project files and build checkpoint

To initialize the Simics project and build additional dependencies, you can run
the following commands, however, you will:

[source,subs=attributes]
----
#  To install Simics, and download additional ependencies, and extract files
make -f config-user.mk simics_setup

#  NOTE: If needed, set SIMICS_BIN (default: {simics_bin})
make -f config-user.mk simics_setup SIMICS_BIN=/some/other/path/bin

#  Create or update CKPT_GLIBC checkpoint (default: {ckpt_glibc})
make ckpt-cc_glibc

#  Create or update CKPT_LLVM checkpoint (default: {ckpt_llvm})
make ckpt-cc_llvm

#  Build Cryptographic Computing Simics modules
make -B
----

Alternatively, you can use the old `./setup_and_build.sh`, or you can use the
`-n` dry-run flag when running make to inspect commands to run separately.


=== (Optional) Build Doxygen codumentation

The follwoing commands creates doxygen documentation for `malloc`, `crypto` and
`modules` under `doc/doxygen`, you can browse the docs by starting from
`doc/doxygen/html/index.html`. The dcoumentation is auto-generated from inline
annotations in comments in the source code files themselves.

----
make documentation
----

=== (Optional) Checkpoint with Ubuntu and custom kernel

Linux has the following additional dependencies (which are auotmatically
installed by `make install_dependencies`):

* bison
* dwarves
* flex
* libelf-dev
* libssl-dev
* llvm

==== Crate initial Ubuntu checkpoint

To set up a Ubuntu checkpoint with a custom kernel, you first need to create a
base Ubuntu checkpoint. This may be done with an automated scripts, but success
may wary, in which case the initial checkpoint must be manually configured:

----
./simics -batch-mode scripts/install_ubuntu.simics
----

When done, use `write-cofniguration {ckpt_kernel_base}` to save a checkpoint.
The scripts by default expect to find the checkpoint at `{ckpt_kernel_base}`,
override `CKPT_KERNEL_BASE` in `config-local.mk` to use different path.

If the script failes, you may need to manually install Ubuntu. To do so, you can
follow the steps found in `scripts/install_ubuntu.simics`. To troubleshoot the
script, run with graphical console enabled; the initial boot will be in the VGA
view, after which GRUB will configure the serial console and continue
installation via that.

==== Update kernel

Once the base checkpoint is created, you should update `config-local.mk` to set
the CKPT_KERNEL_BASE to point where your fresh Ubuntu checkpoint is, and
CKPT_KERNEL to where you want to store your subsequent custom kernel
checkpoints. Once done, you can use the following command to generate a
checkpoint with a custom kernel:

[source,subs=attributes]
----
# Set CKPT_KERNEL_BASE in config-local.mk if needed, (default: {ckpt_kernel})
make {ckpt_kernel}
----

This will create a new checkpoint at CKPT_KERENL.GIT_SHA and create/update a
symlink to it at CKPT_KERNEL.

== Running a workload in Simics

./simics [simics_args] <run_script.simics> [run_arg1=val1 run_arg2=val2 ...]

Useful simics_args (optional):

	-no-win 		run simics with GUI windows hidden (can be displayed on demand)

	-batch-mode		run in batch mode (will exit with 0 on success or non-zero on error)


Most run scripts are based on the generic template scripts/runworkload_common.simics
It supports the following run-time arguments (see default values in the script):

	checkpoint		Specifies the checkpoint.

        system                  Sets the top level module. For QSP use "board" (default), for TGL: "tgl"

	compiler		Overrides the compiler for the workload (unless using custom build command).
				Default: g++

	gcc_flags		Additional compiler flags

	model			Selects the model to run the workload with.
				Values: cc / lim / lim_disp / zts / native. Default: cc
				Note: lim_disp configures the LIM model to perform data displacement instead of shifting.

	run_args		Specifies additional workload run arguments

	env_vars		Overrides environment arguments for the workload run command

	build_cmd		Overrides the default build command

	run_cmd			Overrides the default run command

	pre_run_fixup		Additional bash commands to execute inside Simics before running the workload

	debug			Set to 1 to enable Simics module debug printfs

	download_bin_path	If defined, the workload binary and the compiled libc will be downloaded to the specified host directory.

	disable_meta_check	LIM-only setting. If set to 1, tags and bounds will not be evaluated

	break_on_exeption	LIM-only setting. If set to 1, will stop simulation on exeptions (excl. Page Fault)

	magic			Set to 1 to enable magic breakpoint

	mem_profiler		Set to 1 to enable memory profiler

	run_cycles=N		If set, the workload will run for N billion cycles and pause.
				Default: and stop after completion

	cache			Set to 1 to enable caching model

	exit			Set to 1 to exit on completion (code 0) or error (non-zero code)

Additional run-time arguments for specific scripts:
spec/scripts/generic.simics:

	spec			Specifies the SPEC workload name.

	spec_size		Specifies the SPEC experiment size (test/ref)


Useful examples:

        ./simics spec/scripts/generic.simics spec=libquantum spec_size=test model=lim cache=1

        ./simics unit_tests/runtest_common.simics model=lim workload_name=lim_malloc_test src_path=unit_tests src_file=lim_malloc_test.cpp run_args="--gtest_filter=Calloc*"

== Regression Testing with PyTest:

The test are currently configure do use LLVM's libunwind, consequently you must
use an LLVM checkpoint to run unit tests (e.g., {ckpt_llvm} as described above).

Run all tests (12 jobs in parallel):

[source,subs=attributes]
----
pytest -n12 -v python_tests --checkpoint {ckpt_llvm} [--model native|cc|lim]
----

Run only spec tests:

[source,subs=attributes]
----
pytest -n12 -v python_tests --checkpoint {ckpt_llvm}[--model native|cc|lim]

# all spec workloads:
pytest -n12 -v python_tests/test_spec.py --checkpoint {ckpt_llvm}

# specific workloads:
pytest -n12 -v python_tests/test_spec.py --checkpoint {ckpt_llvm} --spec workload_name [--spec workload_name ...]
----

Run only unit tests:

[source,subs=attributes]
----
	pytest -n12 -v python_tests/test_unit.py --checkpoint {ckpt_llvm}
----

Common options:

	--model			Run tests only with the specified model.
				Can specify multiple by appending '--model <model_name>' for each model
	-d 			load-balance tests.  shortcut for '--dist=load'


== (Optional) pre-commit hooks

To enforce coding guidelines locally, you can install pre-commit hooks that run
tests on the staged changes before allowing a commit to pass. To enable default
commit hooks, you can run

----
#  To install, run:
make pre-commit-install
#  To uninstall, run:
make pre-commit-uninstall
----

The pre-commit hook will apply whitespace fixes automatically to your working
tree, you can inspect those changes using `git diff`, and then add them to your
commit. The pre-commit hook also runs `clang-format` and `cpplint` checks. You
may need to manually adress issues reported by `cpplint`. Cosmetic code style
changes can be automatically applied by running `clang-format -i <filename>`, or
without the `-i` flag to only inspect changes without applying them.

In some cases you may not be able to fix all changes, or may need to commit
files intentionally violate code style rules, to do so, you can always run `git
commit --no-verify`, however, when possible, avoid disregarding issues.
