#                                                              -*- Makefile -*-
# Simics module makefile
#

PYTHON_FILES = module_load.py simics_start.py

MODULE_CLASSES = lim_model lim_model_connection
SRC_FILES += lim_model.c lim_connection.c 

SIMICS_API := latest
THREAD_SAFE = yes

include $(MODULE_MAKEFILE)

